version: '2'
services:
  web:
      container_name: todo-app
      build:
          context: .
          dockerfile: Dockerfile
      image: todo-app
      environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todoappdb
          - SPRING_REDIS_HOST=redis
      ports:
          - "8080:8080"
      depends_on:
        - redis
        - db
      links:
          - redis:redis
          - db:db
  redis:
    image: "redis:alpine"
    ports:
         - "6379:6379"
  db:
    image: postgres
    restart: always
    ports:
         - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoappdb
